version: "3.8"

services:
  oracle_db:
    image: container-registry.oracle.com/database/free:latest-lite
    container_name: oracle-lite
    restart: unless-stopped
    environment:
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
      - "5500:5500"
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/${ORACLE_PASSWORD}@localhost:1521/FREE as sysdba", "@/opt/oracle/scripts/startup.sql"]
      interval: 10s
      retries: 5
      start_period: 10s
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-script.sql:/opt/oracle/scripts/setup.sql

  app:
    build: .
    container_name: bot-app
    restart: unless-stopped
    depends_on:
      - oracle_db
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ORACLE_USER=${ORACLE_USER}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD}
      - ORACLE_DSN=oracle_db:1521/FREE
    volumes:
      - .:/app
    command: ["python", "bot.py"]

volumes:
  oracle-data:

